[package]
name = "ground-station"
version = "0.1.0"
edition = "2024"

[dependencies]
flight-builder = { git = "https://github.com/purdue-orbital/flight-builder.git" }
serde = { version = "1.0.219", features = ["derive"] }
